# Generated by Django 3.1.2 on 2020-11-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Destination',
            new_name='destination',
        ),
    ]
