# Generated by Django 3.1.2 on 2021-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210203_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='receipt',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
