# Generated by Django 3.1.2 on 2021-02-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210204_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='receipt',
        ),
    ]
